import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";


const futura_book_bt = localFont({ src: "./fonts/futura-book-bt.ttf" });

export const metadata: Metadata = {
  title: "DentyTech",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={futura_book_bt.className} style={{ overflow: "hidden" }}>
        {children}
      </body>
    </html>
  );
}
